spring:
  boot:
    admin:
      url: http://localhost:8081
      client:
        enabled: false
  application:
    name: elune-sample-service
    index: ${random.uuid}
  dubbo:
    application:
      name: elune-sample-service-provider
    registry:
      address: zookeeper://localhost:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.outwit.elune.service

server:
  port: 8080
management:
  security:
    enabled: false

druid:
    url: jdbc:mysql://localhost:3306/db_test?verifyServerCertificate=false&requireSSL=true&useSSL=true
    driver-class: com.mysql.jdbc.Driver
    username: root
    password: root
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-While-Idle: true
    test-on-return: false
    pool-prepared-statements: false
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall,log4j,config
    connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false
    monitor:
          enabled: enabled
          druid-stat-view: /druid/*
          druid-web-stat-filter: /*
          allow: 172.20.10.2
          deny: 219.230.50.108
          login-username: druid
          login-password: druid
          exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
          reset-enable: false
mybatis:
  mapper-locations: classpath*:META-INF/mybatis/mapper/*.xml
  type-aliases-package: com.outwit.elune.dao.domain
  type-handlers-package: com.outwit.elune.dao.handler

pagehelper:
  helper-dialect: mysql





